-- AlterTable
ALTER TABLE "Game" ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "psnTitleIds" TEXT[],
ADD COLUMN     "steamAppId" INTEGER,
ALTER COLUMN "genres" DROP DEFAULT,
ALTER COLUMN "developers" DROP DEFAULT,
ALTER COLUMN "platforms" DROP DEFAULT,
ALTER COLUMN "updatedAt" DROP DEFAULT;
